### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by alessandroperetti** [nats-io/nats.ws#100]
I am working on a react app created with create-react-app.
I am using `nats.ws` with the following import as mentioned in README:

`import { connect } from 'nats.ws/nats.js'.`

In a method I am calling:

 `const nc = await connect({servers: 'nats:4442'});`

The compilation process gives me the following fail: 

```
Failed to compile.

./node_modules/nats.ws/nats.js 132:9
Module parse failed: Unexpected token (132:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| class DataBuffer1 {
>   buffers;
|   byteLength;
|
```

Tools versions I am using are: 

react-script@4.0.3
webpack@4.44.2
babel-loader@8.1.0
nats.ws@1.1.2

How can I solve this issue? 

Thank you in advance

**Comment by aricart** [comment]
@alessandroperetti try this https://github.com/nats-io/nats.ws/blob/master/developer_notes.md#working-with-react-create-app
