### ISSUE TITLE
Nats connect not able to parse server options in connect

### ISSUE THREAD

**Issue by dynamite-bud** [nats-io/nats.ws#106]
Nats ws client Connect function is not able to parse the given string in it.
![Screenshot-20210816-055030](https://user-images.githubusercontent.com/41326026/129497409-120e5703-b7ab-46f3-b590-6a3aec7849d4.png)
![Screenshot-20210816-055039](https://user-images.githubusercontent.com/41326026/129497408-820951a3-e24d-4bde-8501-d7915fc592a4.png)
![Screenshot-20210816-055156](https://user-images.githubusercontent.com/41326026/129497402-06414b65-c9eb-4cc1-a8f2-dbaef6ca93f9.png)
![Screenshot-20210816-055147](https://user-images.githubusercontent.com/41326026/129497403-9df12feb-bffe-4e31-9292-9c3209a91af9.png)
![Screenshot-20210816-054759](https://user-images.githubusercontent.com/41326026/129497414-cac8d86c-1a0c-44cb-bb5a-c8748bb9aa9e.png)

I think wsUrlParseFn is not working correctly the input to the function is not correct.

**Comment by aricart** [comment]
@dynamite-bud can you please provide me with your connect options?

**Comment by aricart** [comment]
If I start a nats-server offering wss on 443, and modify [examples/simple.html](https://github.com/nats-io/nats.ws/blob/master/examples/simple.html) to connect like this:
```
const init = async function () {
    // create a connection
    // const nc = await connect({ servers: 'ws://localhost:9222' })
    const nc = await connect({ servers: '127.0.0.1:443' })
    addEntry('connected to NATS!');
```

I get the expected:
```
connected to NATS!
published a message to `hello`
listening for request on `help`
making a request to `help`
got response 'I can help nats request'
closed the connection
```

**Comment by aricart** [comment]
You can run the samples by following https://github.com/nats-io/nats.ws/blob/master/developer_notes.md#developer-notes

If you want to try them with TLS, you'll need to:
- install mkcert - see https://github.com/FiloSottile/mkcert
- npm run install-certs
- npm run start-tls-nats
- npm run start-https
- Click on the link printed by start-https, and navigate to the examples directory.
