### ISSUE TITLE
unable to connect using wss client

### ISSUE THREAD

**Issue by zubairalimansoor** [nats-io/nats.ws#107]
I am getting this error when I enable tls for websocket . Could you please guide how exactly wss can be used ? what need to be done client side? in example I just see url starts with wss instead of wss in case of tls. Please note that I am using tls without authentication. 

TLS handshake error from 127.0.0.1:56566: remote error: tls: unknown certificate authority

server config for websockets
 tls {
       cert_file: "./certs/server-cert.pem"
      key_file:  "./certs/server-key.pem"
	  timeout: 2
     }

**Comment by zubairalimansoor** [comment]
thank you

**Comment by aricart** [comment]
The issue is basically that your self-signed certificate is not trusted because the browser doesn't trust it.
You will want to use something like [mkcert](https://github.com/FiloSottile/mkcert) so you can generate an install the certificates in a way that the system itself trust them.

**Comment by aricart** [comment]
After you install the above tool, you should be able to do something like:

`env CAROOT=./certs mkcert -cert-file ./certs/cert.pem -key-file ./certs/key.pem -install localhost 127.0.0.1 ::1`

Which will install generated certificates in the dir `./certs`. From there you can reference the certificates:

```
port: 4222
websocket: {
  port: 443
  tls: {
    cert_file: "../certs/cert.pem"
    key_file: "../certs/key.pem"
  }
}

**Comment by aricart** [comment]
```

**Comment by zubairalimansoor** [comment]
so I just need to install certificate on server side ? I think this should be solved if I buy certificate from well known vendor , clients who will be connecting from browser won't need to do anything ? correct ?

**Comment by aricart** [comment]
That is correct - however if you buy a certificate you'll need your DNS server to match the certificate details (which will be required to get the certificate). If you are testing locally, you can just use `mkcert`.
