### ISSUE TITLE
Issue with Angular 11

### ISSUE THREAD

**Issue by SeVeNDuS** [nats-io/nats.ws#110]
Hi,

Adding nats.ws to a Angular 11 project is throwing me the following error

Error: ./node_modules/nats.ws/nats.js 131:12
Module parse failed: Unexpected token (131:12)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders. 
| }));
| class Messages {
>     messages;
|     constructor(){
|         this.messages = new Map();

Can you help me?

Regards

**Comment by aricart** [comment]
Try https://github.com/nats-io/nats.ws/blob/master/developer_notes.md

**Comment by aricart** [comment]
Verified that angular 13 works fine.
