### ISSUE TITLE
WebSocket Connection Questions

### ISSUE THREAD

**Issue by byazrail** [nats-io/nats.ws#111]
Hello there,

I am using Nats Server 2.4.0.
I've been using ws-tcp-relay and isobit/websocket-nats websocket integration for a long time.

I installed Nats Server 2.4.0 today.
Incoming requests come as binary.
Outgoing requests from the band go as json.
How can I make outgoing requests from me binary?

I also checked your nats.ws project, but it is available as nodejs.
Not for normal browser use I guess I still use isobit/websocket-nats for browsers.

I've attached an image for the binary examples.
The answers I get are binary.
<img width="1090" alt="Screen Shot 2021-09-09 at 16 56 20" src="https://user-images.githubusercontent.com/5870455/132705734-7c1aa9e4-c5c4-4064-a7a4-e88f7be84507.png">

**Comment by aricart** [comment]
Actually, all the tests run in node.js, the issue you need to solve is to install a WebSocket (there are several) implementations that is browser compliant. For the tests, simply adding the require below does it.
```
const browserEnv = require("browser-env");
browserEnv();
```

**Comment by aricart** [comment]
If you are running on the browser, the nats.ws it runs natively on the browser. Note that the library talks directly to the nats server on its WebSocket port.

**Comment by byazrail** [comment]
> If you are running on the browser, the nats.ws it runs natively on the browser. Note that the library talks directly to the nats server on its WebSocket port.

Thank you for the information;

Before Jan 26, 2018 I was using Socket IO and Redis.
However, it wasn't enough.
I am using Nats-Server and Aerospike after Jan 26, 2018.
I update my own authorization algorithm with each version in the file nats-server/server/auth.go.
I'm using nginx via ws-tcp-relay and isobit/websocket-nats.
Within the request-reply operations, I see my work in pub/sub using golang aerospike and nats-client.
I am working with 6 cluster nodes and 6 aerospike cluster nodes, so far I have not had any problems.

I wanted to write to you because isobit/websocket-nats is not working for me.

**Comment by byazrail** [comment]
*isobit/websocket-nats is no longer sufficient.

**Comment by aricart** [comment]
I have no idea about isobit, you'll have to forward a question directly to them about their library. Currently nats-server directly supports websocket as a transport.

**Comment by byazrail** [comment]
> I have no idea about isobit, you'll have to forward a question directly to them about their library. Currently nats-server directly supports websocket as a transport.

Thank you.

So how can I output the Nats.ws project as dist production?
import { connect } from "nats.ws/nats.js";
instead nats.js?
Nats.connect(etc...); or N.connect(etc...); to use as?

**Comment by aricart** [comment]
Actually super easy - the library ships with two different formats - the cjs (standard node) should be picked if you use `require`. This is how I changed the simple.html sample in the examples to run on node:

```javascript
const { connect, StringCodec } = require("../nats.cjs");
const browserEnv = require("browser-env");
browserEnv();

// add an entry to the document
function addEntry(s) {
  console.log(s);
}

const sc = StringCodec();

const init = async function () {
  // create a connection
  const nc = await connect({ servers: 'ws://localhost:9222' })
  addEntry('connected to NATS!');

  // simple publisher
  nc.publish('hello', sc.encode('nats'))
  addEntry('published a message to `hello`');

  // simple subscriber, if the message has a reply subject
  // send a reply
  const sub = await nc.subscribe('help');
  (async () => {
    addEntry('listening for request on `help`');
    for await (const m of sub) {
      m.respond(sc.encode(`I can help ${sc.decode(m.data)}`));
    }
  })().then()

  // request data - requests only receive one message
  // to receive multiple messages, create a subscription
  addEntry('making a request to `help`');
  const msg = await nc.request('help', sc.encode('nats request'))

  addEntry(`got response '${sc.decode(msg.data)}'`);

  // close the connection
  nc.close();
  addEntry('closed the connection');
}
init();
```

**Comment by aricart** [comment]
Note I wrote the sample in `examples` - when you import, you should just have to do `require("nats.ws")`.

**Comment by byazrail** [comment]
> Note I wrote the sample in `examples` - when you import, you should just have to do `require("nats.ws")`.

Thanks,

I exported nats.ws/nats.cjs using Webpack.

**Comment by aricart** [comment]
@byazrail glad you got it to work

**Comment by byazrail** [comment]
@aricart 
I will fork from the project and share the webpack output as a project and share it with you.

Thank you.
Health to your hands.

**Comment by byazrail** [comment]
@aricart 

Currently working :)

<img width="1118" alt="Screen Shot 2021-09-09 at 22 18 05" src="https://user-images.githubusercontent.com/5870455/132749251-2019008b-52ae-40cf-a882-f126a4143af8.png">

**Comment by aricart** [comment]
@byazrail I believe the issue is one in the packer not selecting the correct library... If you use require, it should just pick the cjs automatically. If you use import it should pick the esm version.

**Comment by byazrail** [comment]
@aricart Is there an example in this system that I can run as dispatch other than asynchronously?
Is it suitable for the dispatch structure?

**Comment by aricart** [comment]
@byazrail javascript is all async - with async/await (like using nc.request) you can simulate sync behaviour, but it is async. JavaScript is single threaded, run to completion, so that means that if it is busy doing something, it cannot do anything else. If you give me an example of what you are trying to do maybe I can help a bit more.

**Comment by byazrail** [comment]
@aricart 
Sample;
nc.subscribe("hello");
var customSocket = nc.connect('params');
customSocket.on('hello', function (data) {
console.log('hello received : ', data);
});

// Another
customSocket.request('request', {type: key}, {'max' : 1}, function(getData)
{
	customSocket.dispatch(key, getData);
});

//
customSocket.on(key) // key : connect, disconnect, reconnect, own pub/sub keys, request response key etc.

I have a system of my own, when I subscribe to a channel, when a data comes to that channel, I will listen to customSocket.on('hello') and process the incoming data.

This is how I do it in golang php etc clients.
I provide data transfer as in the example I gave in the nats-client I used before.
I also dispatch and direct it in my own library.

**Comment by aricart** [comment]
I think you are confusing callbacks with async/sync. If you are looking for callbacks this works:

```
const nc = await connect(opts);
nc.subscribe("hello", {callback: (err, msg) => {
 // do something
}})
```

For requests you can do the following:
```
const r = await nc.request("request");
```
You can also deal with the promise:
```
nc.request("request").then((m)=>{ // do something}).catch((err) => { // do something with the error}) 
```

In most cases using async pattern is simpler since you can interrupt the flow until the processing completes/fails, without having to chain. In all cases, where the inline function was provided, you can specify a function argument

**Comment by byazrail** [comment]
Request and Subscription works fine.

This is how I use it for subscription.
```
subscribe: function(eventName)
{
     base64Name = base64Encode(eventName);
     customSocket.subscribes[base64Name] = customSocket.socket.subscribe(eventName, {callback: (err, m) =>
     {
         console.log(jc.decode(m.data));
         customSocket.dispatch(eventName, jc.decode(m.data));
     }});
}
```

I could not see unsubscribe for subscription cancellation, I defined it as flush unsubscribe, but there was no solution.

What do you recommend for unsubscribe?

unsubscribe function;
```
unSubscribe: function(eventName)
{
     var base64Name = base64Decode(eventName);

     if (customSocket.subscribes[base64Name])
     {
         console.log(customSocket.subscribes[base64Name]);
         customSocket.subscribes[base64Name].unsubscribe();
         /*
         customSocket.socket.unsubscribe(customSocket.subscribes[base64Name]);
         delete customSocket.subscribes[base64Name];
         delete customSocket.callbacks[eventName];
         */
     }
}
```

**Comment by byazrail** [comment]
Correct Unsubscribe action;

```
unSubscribe: function(eventName)
{
     var base64Name = base64Decode(eventName);

     if (customSocket.subscribes[base64Name])
     {
         customSocket.subscribes[base64Name].drain();
         delete customSocket.subscribes[base64Name];
         delete customSocket.callbacks[eventName];
     }
}
```

**Comment by aricart** [comment]
the object returned from `subscribe()` has `unsubscribe()` and drain() so you can fully process the messages waiting in the subscription. If you know the number of messages you are processing ahead of time, you can subscribe and immediately unsubscribe for the count.

**Comment by aricart** [comment]
Also a JavaScript thing, you may want to use new Map<string,Sub>(), instead of using the object as a map. Usually, linters don't like that type of usage.

**Comment by byazrail** [comment]
@aricart Thank you so much.
It has been a very successful WebSocket client.
I no longer use async.
I don't like 3rd party software, I'm glad WebSocket is here :)

Best wishes...
