### ISSUE TITLE
Golang wasm client

### ISSUE THREAD

**Issue by gedw99** [nats-io/nats.ws#112]
I know this is a js client but I am wondering if the Team is likely to consider a golang client . 

Tinygo is now usable and makes building gui apps with golang and wasm realistic .

I am doing it this way .

**Comment by gedw99** [comment]
Looks like I missed an issue related : https://github.com/nats-io/nats.go/issues/530

**Comment by aricart** [comment]
Nats.go already implements this as of 1.11?

**Comment by gedw99** [comment]
thanks @aricart Will have a look. thanks you telling me :)
