### ISSUE TITLE
Compilation error in vue environment

### ISSUE THREAD

**Issue by beanhacker** [nats-io/nats.ws#116]
ERROR  Failed to compile with 1 error                        10:20:30 ├F10: AM
┤

 error  in ./node_modules/_nats.ws@1.3.0@nats.ws/nats.js

Module parse failed: Unexpected token (131:12)
You may need an appropriate loader to handle this file type, currently no loader
s are configured to process this file. See https://webpack.js.org/concepts#loade
rs
| }));
| class Messages {
>     messages;
|     constructor(){
|         this.messages = new Map();

**Comment by reno1979** [comment]
same here with a vanilla js project; 

```
import { connect } from 'nats.ws/nats.js';
```

will not build using rollup. I managed to get it working when changing this part of the package.json of the nats.ws module:

```
"exports": {
    ".": {
      "require": "./nats.cjs",
      "default": "./nats.js"
    }
  },
```` 

to 

```
"exports": {
      "require": "./nats.cjs",
      "default": "./nats.js"
  },
````

**Comment by zacharya19** [comment]
I had the same issue, and I found a workaround: importing `nats.cjs` instead of `nats.js` 

> You may want to try: https://github.com/nats-io/nats.ws/blob/master/developer_notes.md#older-typescript-compiler

I tried that, I am using VueJs as well, and this solution sadly doesn't work :disappointed:

**Comment by Kjir** [comment]
To fix the error in OP you have to transpile `nats.ws` with babel.
If you're using the Vue CLI you can add the following to your `vue.config.js`:

```
  transpileDependencies: ["nats.ws"],
``` 

However unless you're using webpack 5 it will then fail because the optional chaining syntax isn't supported by acorn 6.x (which webpack 4 uses). Webpack 5 is only available with the beta of the next Vue CLI version.

**Comment by aricart** [comment]
@kjir @zacharya19 @reno1979 @beanhacker 
I have adjusted the bundle packaging. At the very least now a properly shimmed node environment (with websocket installed) can use both the cjs and esm libraries. Wondering if this will also pacify other bundlers (outside of the optional chaining which should be addressed by the bundlers).

Can you try `npm install nats.ws@next` - you should get `nats.ws@1.6.1-2`

I will try the same on next.js.

**Comment by aricart** [comment]
I have verified next.js works fine with the new bundle.

**Comment by aricart** [comment]
Also verified that react works correctly

**Comment by aricart** [comment]
Did a simple project, and I am able to load the esm library from above correctly and connect to a server.

**Comment by reno1979** [comment]
This is great, it seems to work in our setup using rollup with js es modules!

**Comment by aricart** [comment]
Fixed by https://github.com/nats-io/nats.ws/pull/126
