### ISSUE TITLE
Refreshing the JWT token

### ISSUE THREAD

**Issue by Kjir** [nats-io/nats.ws#124]
Hello,
we are trying to use NATS in the browser through websockets for our web application. Following best practices around JWT management, we have an access token and a refresh token kind of system, with the access token being short lived and the refresh token  being longer lived. This is to minimize the risk of someone stealing the token and being able to access the application for a long time.

We want to reproduce the same using NATS with JWT authentication. Our user-JWT has the same length as the access token (15 minutes) and by my understanding this would mean that the WS connection gets closed after the JWT expires. We would like to have a way to update the credential of the connection: we can issue a new user-JWT using the refresh token, but I don't see a way to tell NATS to use the new token without closing and reopening the connection - which could lead to losing some events on our subscriptions.

Is there a way to do this? What is the best practice with NATS and JWT when the JWT is in the hands of an untrusted client (the user's browser)?

**Comment by aricart** [comment]
@Kjir yes currently the server doesn't provide an async mechanism where it requests the client to re-authenticate prior to disconnection. I believe this has been discussed and it is in the plan.

As for strategies to handle this situation, there are many - httpOnly is the first step. Now the reason for your question usually means that the client is not trusted, but also that the client may be able to do something that it is not supposed to do, and that by reducing the session time the window for that sort of problem is usually acceptable.

Are your permissions fairly clamped - ie are the permissions for the user things where your application can determine provenance?

In this example https://github.com/aricart/authdemo/blob/master/main.go#L161 (may be a bit out of date) - the jwt's issued to the client are clamped to an identifier for the user. This means that the only client that can send messages that identify the client precisely. The application can then verify and handle the request. 

The point here is that if you have some sort of protocol for the client initiating and ending a session, you could in fact make the session invalid by revoking the client. At that point reconnection using the JWT will fail. So you could make your session JWT live longer, knowing that on the server-side you'll control the life of the token and terminate it once the user is done.

**Comment by Kjir** [comment]
In my use case, I have a web app that subscribes to some topics so that I can update the information in real time as other users change it. The problem is that on the one hand I don't want users to reconnect every ~15 minutes, possibly losing messages in the process, but on the other hand I worry that if an attacker gains access to the user-JWT they can silently receive all the updates - so all the data - that the users are putting in.

**Comment by aricart** [comment]
Yes, currently we don't have support for this feature - but it is on the road map. For now, the alternatives above are the only posibility.

**Comment by lewisl9029** [comment]
I also have a use case that could use a more ergonomic token refresh flow.

Can we reopen this issue and close it when the feature has been implemented, so we can follow for updates?

**Comment by aricart** [comment]
Revocations happen on the account JWT. I am going to assume that you know how to build the JWTs using the jwt (go lib) or the javascript library - In terms of the model, the node is `revocations` and it is a Record of public key to UNIX time for the revocation. The key, can be `*` which means all JWTs issued on or before the UNIX time listed:

```json
{
 "iat": 1664375621,
 "iss": "OCJVKCDU7XDY2PAATYNJOHX4MB32EICFHB3SWCU5WJH6OLUE4QSBG7A4",
 "jti": "IS7WWGZNTI6K5YF6TM3VYBSA7OGD44PWMCARO6NL2T7ETIMG2OUA",
 "name": "A",
 "nats": {
  "default_permissions": {
   "pub": {},
   "sub": {}
  },
  "limits": {
   "conn": -1,
   "data": -1,
   "exports": -1,
   "imports": -1,
   "leaf": -1,
   "payload": -1,
   "subs": -1,
   "wildcards": true
  },
  "revocations": {
   "*": 1664375621,
   "UBHB4ZRFHVLOANQGGBWFQ5CEN4PVNHCU2YA5PDMM7NFLJK3ACSR2WQTC": 1664375623
  },
  "type": "account",
  "version": 2
 },
 "sub": "ADPKPH7767Z6SHPZUJNDAONKSZ24FPMQW4OH3K2ZNE3GMH23QJOJ3YW7"
}
```

Note that all JWTs older than `11664375623` and for user `UBH...` all JWTs older than `1664375621`.


Another approach to revocation is to use account signing keys. You can, for example, rotate 10 signing keys (issuing one every minute or whatever is convenient), and then add a new key every interval while deleting the oldest one at the same interval, which means that sessions will only survive the key rotation interval, and you won't have to track them individually. 

Or you can keep updating the `*` entry to revoke all users older than 10m, etc. In all cases, with the exception of user JWTs that have an expiration set, you'll have to track yourself. The best way is to just put in some sort of expiration on the JWT, but that means that the connection will have to reset on every update even if you proactively manage two different connections during the session transition. At some point, the server will allow you to update (this has been discussed), which will simplify this process for frequently rolled JWTs.

**Comment by yordis** [comment]
@aricart I need immediate revoking, I wonder if that is possible now, or if there is a upstream issue to follow this.

cc: @derekcollison
