### ISSUE TITLE
Package subpath './nats.js' is not defined by "exports" in /app/node_modules/nats.ws/package.json

### ISSUE THREAD

**Issue by adhocmaster** [nats-io/nats.ws#125]
Hi there,

I am trying to import it this way:

import { connect } from "nats.ws/nats.js";

I tried both 1.5.0 and 1.6.0

**Comment by aricart** [comment]
@adhocmaster what is your runtime? - node/browser?

Can you try a `npm install nats.ws@next` and tell me if that behaves differently for you.

**Comment by aricart** [comment]
(the above should install `nats.ws@1.6.1-2` for you. Thanks!

**Comment by adhocmaster** [comment]
Hi @aricart Thank you. I will try it next. BTW, I am doing this now instead:

const {connect} = require("nats.ws")

I haven't fully tested it yet, but the import error is gone.

**Comment by aricart** [comment]
Yes the fix is that prob node or webpack etc was not resolving as it was correctly - Please reopen if you don't solve the problem, but I believe it is fixed.

**Comment by adhocmaster** [comment]
nats.ws@1.6.1-2 is not working either. When I looked in the package.json file of the module I found:

exports have been changed:
```
  "exports": {
    ".": {
      "require": "./cjs/nats.js",
      "import": "./esm/nats.js"
    }
  }
```
So, import { connect } from "nats.ws/nats.js" gives a module not found error. So, I changed "nats.ws/nats.js" to "nats.ws" hoping that it will import "./esm/nats.js". Interestingly, this imports the connect method.

**Comment by adhocmaster** [comment]
Created a pr to update the readme file. Thanks,
Muktadir
