### ISSUE TITLE
Missing documentation for client certificates authentication

### ISSUE THREAD

**Issue by mcosta74** [nats-io/nats.ws#136]
The REAMDE file mentions that is possible to use client certificates as Authentication scheme (https://github.com/nats-io/nats.ws/blob/main/README.md#authentication) but there's no documentation on how to do it,

There're only examples for NKEY and JWT

**Comment by aricart** [comment]
nats.ws doesn't support them since they target the webbrowser and the api doesn't provide a hook for that.

**Comment by mcosta74** [comment]
> nats.ws doesn't support them since they target the webbrowser and the api doesn't provide a hook for that.

would be possible to say that in the documentation?

**Comment by mcosta74** [comment]
is it enough to drop this row in the documentation or we need to specify why ?

**Comment by aricart** [comment]
Simply say that we are using a W3C websocket, and those APIs don't provide client certificate authentication. - On the repo for [nats.deno](https://github.com/nats-io/nats.deno) which hosts the common code for all the javascript clients, it simply says that "`tls` is not supported on websocket"

**Comment by mcosta74** [comment]
Yes,
I'll do

Massimo Costa

Il sab 26 feb 2022, 22:53 Alberto Ricart ***@***.***> ha
scritto:

**Comment by mcosta74** [comment]
I've open a PR #139

**Comment by aricart** [comment]
@mcosta74 Grazie Mille
