### ISSUE TITLE
"NatsError" when attempting to connect via mTLS

### ISSUE THREAD

**Issue by DoisKoh** [nats-io/nats.ws#140]
Hello,

On `nats:2.7.3-alpine3.15` (server), with `verify=true` (I want mutual TLS), providing certs made with `mkcert` leaves me with an unknown error from nats.ws, and the NATS server saying `TLS handshake error from...: EOF`

I've reached the point where I'm guessing there might be a bug with nats/nats.ws - could this be a known issue?

Thanks.

**Comment by aricart** [comment]
@DoisKoh the nats.ws client doesn't support tls options - it requires a w3c websocket which doesn't allow this configuration to happen in browser, etc.

https://github.com/nats-io/nats.ws#tls-and-client-certificates
