### ISSUE TITLE
Websocket TLS handshake error EOF

### ISSUE THREAD

**Issue by game5413** [nats-io/nats.ws#141]
Hello, currently i'm trying to setup nats websocket with tls based example configuration on this [reference](https://docs.nats.io/running-a-nats-service/configuration/websocket/websocket_conf) on my local environment, tls that i'm use was self signing certificate from mkcert, then mounting them into docker container alongside with my nats server configuration.

nats-server.conf
```
# Client port of 4222 on all interfaces
port: 4222

# HTTP monitoring port
monitor_port: 8222

authorization {
	default_permissions: {
		publish: "SANDBOX.*"
		subscribe: ["PUBLIC.>", "_INBOX.>"]
	}
	ADMIN: {
		publish: ">"
		subscribe: ">"
	}
	WS_USER: {
		publish: ["cmd.req", "_INBOX.>"]
		subscribe: ["notifications.*", "_INBOX.>"]
	}
	users: [
		{ user: admin, password: "admin", permissions: $ADMIN, allowed_connection_types: ["STANDARD"] }
		{ user: user, pass: "user", permissions: $WS_USER, allowed_connection_types: ["WEBSOCKET"] }
	]
	timeout: 15.0
}

# This is for clustering multiple servers together.
cluster {
  name: "executive-nats-cluster"

  port: 6222

  authorization {
    user: "cUser"
    password: "cPassword"
    timeout: 2
  }

  routes = []
}

websocket {
    port: 6969

    tls {
          cert_file: "/etc/nats/mkcert-server-cert.pem"
          key_file: "/etc/nats/mkcert-server-key.pem"
    }

    authorization {
		timeout: 3.0
    }
}
```
With config above, i'm tried connecting to websocket using [nats.ws](https://github.com/nats-io/nats.ws) as client, with example code like below, and got an error message unknown error

![image](https://user-images.githubusercontent.com/37659721/157583054-1be11514-3072-4e2e-aa51-36c8cd6b012e.png)

after that, i'm checking container logs on docker and see an error logs that say `TLS handshake error EOF` like on picture below

![image](https://user-images.githubusercontent.com/37659721/157582074-2e89fb0c-2d49-48e3-9fe3-6e6d8370d44f.png)

Is there a limitation from nats.ws ? i've already tried to pass tls certificate into connect method and still not work. When i'm check the documentation it was updated to clarify that websocket can't connect using tls on this [reference](https://github.com/nats-io/nats.ws#tls-and-client-certificates). Then how i'm supposed todo for connecting to websocket with TLS because from the websocket [configuration](https://docs.nats.io/running-a-nats-service/configuration/websocket/websocket_conf) they said tls was enabled by default and inject with `no_tls: true` only for test env.

**Update**
I'm trying with another client library and that was [nats.go](https://github.com/nats-io/nats.go), it can properly connected with tls configuration on nats server. It seems that was issue on nats.ws, can you fix it ?

![image](https://user-images.githubusercontent.com/37659721/157638501-2dbc00dc-d95d-4d91-9bf6-e0c12c61d5df.png)
![image](https://user-images.githubusercontent.com/37659721/157638448-0a6557e2-342a-4c56-9a9b-b01792c8eb1e.png)

Environment:

- Windows 10 Pro 21H2
- WSL2
- Docker Desktop

**Comment by aricart** [comment]
Yes nats.ws doesn't support TLS configuration as it uses  W3C websocket, which don't provide a way to hook them up.
