### ISSUE TITLE
error: new TextEncoder()

### ISSUE THREAD

**Issue by tmnhut97** [nats-io/nats.ws#143]
react-native not working TypeError: undefined is not a constructor (evaluating 'new TextEncoder()')

**Comment by tmnhut97** [comment]
fixed

**Comment by SunChero** [comment]
can you share how did you get this fixed .. i m having the same issue 
thank you

**Comment by tmnhut97** [comment]
Your problem is on react-native right ?

Vào 01:01 PM, T.7, 6 Th8, 2022 Adil Ha ***@***.***> đã viết:

**Comment by SunChero** [comment]
yep the problem is with expo/react-native

**Comment by tmnhut97** [comment]
// nats on react native
yarn add react-native-url-polyfill text-encoding
import 'react-native-url-polyfill/auto'; // on index.js
add import {TextEncoder} from "text-encoding"; // on node_modules\nats.ws
\lib\nats-base-client\encoders.js
This is how I fixed it on react-native, hope it helps

Vào 09:26 AM, CN, 7 Th8, 2022 Adil Ha ***@***.***> đã viết:

**Comment by tmnhut97** [comment]
this is in the discussion section of github

Vào 11:50 AM, CN, 7 Th8, 2022 Minh Nhứt Tô ***@***.***> đã viết:
