### ISSUE TITLE
Subscription object is non-iteratable in react-native typescript

### ISSUE THREAD

**Issue by fiianalytics** [nats-io/nats.ws#152]
React native: 0.68
nats-ws: 1.8.1

We are using nats from the below path:
`import { ConnectionOptions, NatsConnection, StringCodec, Subscription } from '[nats.ws/lib/src/mod](http://nats.ws/lib/src/mod)';`

Nats is getting successfully connected, and we are subscribing to a topic. 
On trying to loop the subscription response we are getting the following issue: 

`LogBox.js:173 Possible Unhandled Promise Rejection (id: 6):
TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`

We must fallback to using callbacks again. Is there any other solution for this?

**Comment by aricart** [comment]
@fiianalytics can you give me a better context on where the subscription is created? if this is jetstream, did you await the subscription?

The subscriptions are all iterable unless you provide a callback.

**Comment by aricart** [comment]
The import is wrong.   Make sure you have the latest, of nats.ws, and react native.   Importing just form 'nats.ws', should be all you need.  If you don't, that means that the react stack is not current and the bundler is old.  If that is the case you can try importing nats.ws/cus/nats.js. If you are using edm modules, import nats.ws/esm/nats.js. no other import should be required.

**Comment by aricart** [comment]
The import is wrong.   Make sure you have the latest, of nats.ws, and react native.   Importing just form 'nats.ws', should be all you need.  If you don't, that means that the react stack is not current and the bundler is old.  If that is the case you can try importing nats.ws/cus/nats.js. If you are using edm modules, import nats.ws/esm/nats.js. no other import should be required.

From the look of it you are using import so try esm.

**Comment by aricart** [comment]
@fiianalytics any luck?
