### ISSUE TITLE
prebuilt package ?

### ISSUE THREAD

**Issue by setop** [nats-io/nats.ws#155]
Hi,

Is there a way to just import the package in an HTML page, without needing to build it locally (no node, no npm) ?

Like

```
<script src="https://wondercd.tld/path/to/nats.min.js"></script>
```

Would be convenient.

**Comment by aricart** [comment]
Yes you can download the npm and copy esm/nats.js file and put on your
webserver.  This is a manual operation when you want to update the library.
The esm version is packaged in the npm bundle fully built. You don't need
any additional bundler etc to use it.

**Comment by setop** [comment]
Hi Alberto,

Thanks for your quick reply. Was useful.

I found it:

```bash
wget https://registry.npmjs.org/nats.ws/-/nats.ws-1.8.1.tgz
tar xfz nats.ws-1.8.1.tgz package/esm/nats.js
mv  package/esm/nats.js ./
./webserver
```
then in the html page
```javascript
import { connect } from "./nats.js";
const conn = await connect({
	servers: ["wss://demo.nats.io:8443"]
});
```
It works 

Thank you very much
