### ISSUE TITLE
Angular 13.1  Nats.ws client dose't send CONNECT message after receiving INFO message 

### ISSUE THREAD

**Issue by Mekasan** [nats-io/nats.ws#157]
Hi guys, got strange behaviour:
Angular 13.1 client dose't send CONNECT message after receiving INFO message and after some time TIMEOUT error.
Same error when I trying to run nats.ws with deno. 

I am rewriting app from angular 1 to angular 13 in old app nats works fine with https://www.npmjs.com/package/websocket-nats

**Comment by aricart** [comment]
Also - if you are using nats.ws, the code you have most definitely won't work - the library has a completely different API than the 1.x nats.js that is used by the websocket-nats.

**Comment by izwerg** [comment]
This is a text/binary websocket issue:
<img width="1436" alt="Screen Shot 2022-08-12 at 12 20 18" src="https://user-images.githubusercontent.com/7271996/184329445-b79f1427-90e2-42b0-97cd-b97956c7c8cb.png">

**Left picture**
Test local NATS 2.2 server with native websockets enabled. `nats.ws` works fine.

**Right picture**
Legacy production NATS 1.1 server with custom [nats-websocket-gw](https://github.com/izwerg/nats-websocket-gw). This approach works well with ancient [websocket-nats](https://github.com/isobit/websocket-nats).

Is there a way to switch to a text websocket in `nats.ws`?

**Comment by aricart** [comment]
Unfortunately, not at this time, it is expecting to communicate in binary as the nats-server supports. On the server-side I am guessing that you are proxying the nats-server TCP port (4222) to your websocket gateway?
