### ISSUE TITLE
kNWErrorDomainPOSIX error when try to connect

### ISSUE THREAD

**Issue by Autoshi-k** [nats-io/nats.ws#160]
Hey
When I try to connect my nats server with iOS, I get error:
WebSocket connection to 'wss://...' failed: ... (kNWErrorDomainPOSIX error 96- Mo message available on STREAM)
same code on android or browser works well

`nc = await connect({
          reconnect: true,
          maxReconnectAttempts: -1,
          reconnectTimeWait: 2 * 1000,
          pingInterval: 10 * 1000,
          servers: conf.natsServer, 
          user: conf.natsUser, 
          pass: conf.natsPassword
        })`

this is the error event:
![image](https://user-images.githubusercontent.com/89990659/185929689-8c72d7f0-98be-477b-8ef4-bbcbf81b44e2.png)
if you need more details please let me know

thank you

**Comment by Autoshi-k** [comment]
We figured iOS does not support compression so we disabled it on the server,
is there a way to disable it while connecting the server in client side?

**Comment by aricart** [comment]
Unfortunately, the client doesn't negotiate this setting. By the time the client connects, the WebSocket is already compressed.

**Comment by guybrand** [comment]
Do you possibly know if there's a way on the server side (nats) to either:
identify the client type (or some header from client side during the http negotiation and before the upgrade)  and set compression accordingly (during the upgrade) ?
set two different ports on the same nats server - so web/android would connect via a compressed session, and ios not, something like:

websocket: {
  port: 9222
  no_tls:false

  compression: false
  tls {
    cert_file: "crt/server.crt"
    key_file:  "crt/server.key"
  }
}

websocket1: {
  **port: 9333**
  no_tls:false

  compression: false
  tls {
    cert_file: "crt/server.crt"
    key_file:  "crt/server.key"
  }
}

**Comment by aricart** [comment]
@kozlovic can maybe respond. I don't believe there's a hook (server is just using whatever you configure), and it doesn't do multiple ws ports, but perhaps there's something I am not aware of.

Now one thing I am puzzled about is that I have tried connecting from iOS via safari (I believe all applications use the same mechanism). I am going to try again with compression and see if that works.

**Comment by guybrand** [comment]
@kozlovic - thanks for the detailed response, yet reading through the tickets, I'm not sure what the status is for nats,ws .

https://github.com/nats-io/nats-server/issues/2612 ends with a suggestion to use flush on server side and "splitting frames... **so will work with @aricart to fix that**."


https://github.com/nats-io/nats-server/pull/2613 states:

... Then, fragmentation of compressed frames are not processed
correctly by Safari (all other browsers and websocket
libraries reassemble them well). **So disable compression + fragmentation
for Safari browsers.**

I do see the code change identifies User-Agent - Contains(ua, "Safari").

So (assuming we **are** using nats.ws) does that mean:
1. Update my nats server
2. return compression: true

would "resolve" the problem by compressing packets coming from none Safari browser, or do we still have issues with splitting frames ?

**Comment by kozlovic** [comment]
> ends with a suggestion to use flush on server side and "splitting frames... so will work with @aricart to fix that."

No, this change was made in the NATS Server, so nothing to do here in the client library.

> So disable compression + fragmentation for Safari browsers.

Yes, what it means is that the server (in the aforementioned PR) makes sure to not fragment compressed frames for Safari browsers.
