### ISSUE TITLE
Error when using `os.get()` to download file from object store

### ISSUE THREAD

**Issue by jmordica** [nats-io/nats.ws#164]
I hate to keep blowing you guys up. You've been great. Hopefully this is the last issue *cough cough*.

I'm attempting to download a file in the object store using NodeJS 16.16.x. It fails (unless I upload an encoded string and try to download it was encoded `sc.encode("some string");`)

When trying to download an object that was uploaded as an encoded string `sc.encode("some string");`, downloading the object works fine and I can decode the object, save the chunks to a file and/or log them.

------------------

I know the file i'm uploading is uploaded properly because I can `get` the file using the nats cli and the file opens properly.

```js
const obj = await this.os.get('latest/latest.sql.gz');
if (obj === null) return null;

await this.fromReadableStream(obj!.data);
```
```js
async fromReadableStream(rs: ReadableStream<Uint8Array>) {
  const reader = rs.getReader();
  // WE ARE GETTING HERE. `reader` looks good
  let i = 1;
  while (true) {
    // WE ARE NOT GETTING HERE. SEE ERROR BELOW FROM NATS-SERVER
    const { done, value } = await reader.read();
    if (done) break;
    console.log(`Chunk ${i++}`);
    if (value && value.length) {
      console.log(`chunk: ${value}`);
    }
  }
}
```

```
NatsError: unable to recreate ordered consumer OBJ_my-stream at seq 1
at /myproj/node_modules/nats.ws/nats-base-client/jsclient.ts:724:22
code: 'REQUEST_ERROR',
chainedError: NatsError: stream name in subject does not match request
at checkJsErrorCode (/myproj/node_modules/nats.ws/nats-base-client/jsutil.ts:205:14)
........
    code: '400',
      chainedError: undefined,
      api_error: {
        code: 400,
        err_code: 10056,
        description: 'stream name in subject does not match request'
    }
  }
}
```

Thanks for any pointers here.

**Comment by aricart** [comment]
I assume this is the reading side of https://github.com/nats-io/nats.deno/issues/357

Can you compare the code where you do the `put` and where you do the `get` for the object store initialization? The error above is simply saying that the subject we are using doesn't match, so

**Comment by aricart** [comment]
You can also do:

const nci = nc as NatsConnectionImpl;
nci.options.debug = true;

which will output what the client is sending

**Comment by aricart** [comment]
also make sure your client/server versions are up-to-date.

**Comment by aricart** [comment]
@jmordica I believe this was sorted out - there were inconsistencies in some of the changes introduced in Go and the javascript library which were resolved. If you find another issue please feel free to reopen.

**Comment by jmordica** [comment]
Thanks for the follow up! Good to go.
