### ISSUE TITLE
WebSocket connection retry handling is severely broken in Firefox

### ISSUE THREAD

**Issue by heikkilamarko** [nats-io/nats.ws#172]
Setup:

OS: Mac Monterey v12.4
Firefox: 106.0.5 (64-bit)
NATS Server: v2.9.6
nats.ws: v1.10.0,

```
# server.conf

websocket {
    port: 9222,
    no_tls: true
}
```

```js
// Web app

conn = await connect({
	servers: config.URL,
	maxReconnectAttempts: -1, // Retry forever
	waitOnFirstConnect: true
});
```

Steps to reproduce:

1. Start NATS server with WebSockets enabled.
2. Open your web app in Firefox. The app connects to the NATS server's WebSocket endpoint.
3. Everything is fine.
4. Stop the NATS server for 3 minutes or so.
5. Start the NATS server again.
6. After a while, the web app connects to NATS server by establishing **several WebSocket connections!**
7. There should be only one connection, instead of 7 or so.

This happens only in Firefox. Chrome and Safari work without problems.
I tried both localhost and non-localhost setups.

This is most probably related to this Firefox behavior (see the accepted answer):

> Found it. This is intentional behavior to comply with RFC 6455. Per this patch, it uses an exponential backoff up to 60 seconds max. Unfortunately I think this means auto-reconnecting to a websocket endpoint in Firefox is broken.

- https://stackoverflow.com/questions/59548618/firefox-doesnt-close-websocket-immediately-on-connection-error
- https://bugzilla.mozilla.org/show_bug.cgi?id=711793

I took some screenshots from Chrome (left) and Firefox (right) where this exponential backoff is clearly visible:

<img width="2040" alt="screenshot_01" src="https://user-images.githubusercontent.com/3757314/200159102-ed96151f-a3b9-4103-b7ec-6d9fef419c10.png">

Here you see how multiple connections (should be only one) are established after restarting the NATS server. You can see the connections in NATS server's http://localhost:8222/connz endpoint too, or by running `nats server report connections` from command line.

<img width="1017" alt="screenshot_02" src="https://user-images.githubusercontent.com/3757314/200159113-a6961ab7-76a6-44e6-aae1-35dcdbc9e5ff.png">

**Comment by bruth** [comment]
@heikkilamarko Thanks for the report (and sorry for the delay). I confirmed this behavior as well. It does not appear to be an issue in Chrome (after another local test).

**Comment by bruth** [comment]
I understand the desire to comply with the RFC and do the expotential backoff with a max of 60 seconds, but it seems like each retry attempt (after some point) is opening a new connection rather than keeping one around. So then when it can finally reconnect, all previous attempted connections now get established.

I doubt this is something that can be solved in nats.ws, unless there is a way to override/shim the retry behavior. Otherwise, we should just put a note on the README calling this out for Firefox.

@aricart any thoughts?

**Comment by aricart** [comment]
I have not commented on this because as @bruth mentions it is possible that there's not much we can do. This is on my radar, and I suspect there may be something we can do, I just need to verify if my suspicion is correct.

**Comment by aricart** [comment]
@heikkilamarko actually - that was a small expedition - the firefox debugging tab shows you (and traces) all the ws connections that were opened - but really there's only one that is actually running. You can verify this by pointing your browser at the server's monitoring port, and seeing the number of connections.

The client properly issues a close() on the transports that fail to handshake within the expected amount of time.

**Comment by aricart** [comment]
also did a little test where I collect all the WebSocket created, and check on the status
```javascript
 constructor() {
    this.version = VERSION;
    this.lang = LANG;
    this.connected = false;
    this.done = false;
    this.socketClosed = false;
    this.encrypted = false;
    this.peeked = false;
    this.yields = [];
    this.signal = deferred();
    this.closedNotification = deferred();

    WsTransport.monitor();
  }

  static monitor(): void {
    if(monitoring) return;

    monitoring = true;

    setInterval(() => {
      function rs(s: WebSocket): string {
        switch(s.readyState) {
          case 0: return "CONNECTING";
          case 1: return "OPEN";
          case 2: return "CLOSING";
          case 3: return "CLOSED";
          default: return "?????";
        }
      }
      const t = sockets.map((s, idx) => {
        const status = rs(s);
        return {idx, status}
      });
      console.log(t);
    }, 2000)
  }
```

```
Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
​
0: Object { idx: 0, status: "CLOSED" }

1: Object { idx: 1, status: "CLOSED" }

2: Object { idx: 2, status: "CLOSED" }
​
3: Object { idx: 3, status: "CLOSED" }
​
4: Object { idx: 4, status: "CLOSED" }
​
5: Object { idx: 5, status: "OPEN" }
​
length: 6
​
<prototype>: Array []
nats.js:9718:21

```

**Comment by heikkilamarko** [comment]
I prepared a minimal repro. I see the problem every time I run the following setup in Firefox.

JavaScript:
```js
import { connect, StringCodec } from "nats.ws";

document.querySelector("#app").innerHTML = `
  <div>    
    <h1>nats.ws firefox problem</h1>
    See the browser console for duplicate messages.
  </div>
`;

subscribe();

async function subscribe() {
  try {
    const conn = await connect({
      servers: ["ws://localhost:9222"],
      name: "demo-ui",
      maxReconnectAttempts: -1,
      waitOnFirstConnect: true,
    });

    const sub = conn.subscribe("demo.>");

    const codec = StringCodec();

    for await (const msg of sub) {
      try {
        console.log({
          subject: msg.subject,
          data: codec.decode(msg.data),
        });
      } catch (er) {
        console.error(err);
      }
    }
  } catch (err) {
    console.error(err);
  }
}
```

NATS config:
```
server_name: demo

http_port: 8222

websocket {
    port: 9222,
    no_tls: true
}
```

Message sending command:

```bash
nats pub demo.message "test {{.Count}} [{{.TimeStamp}}]" --sleep 5s --count 0
```

- Open the web app in Firefox. The app connects to the NATS server's WebSocket endpoint.
- Everything is fine.
- Stop the NATS server for 3-5 minutes or so.
- Start the NATS server again.

Here are some screenshots where the problem is visible. Duplicate connections and messages. Notice that the extra connections are first without names, and then suddenly they are replaced with connections with the `demo-ui` name. Follow the `Uptime` column.

<img width="1378" alt="screenshot_1" src="https://user-images.githubusercontent.com/3757314/205142746-b46e68c2-6e8d-4903-b74f-402a8d2bd0ec.png">

<img width="1371" alt="screenshot_2" src="https://user-images.githubusercontent.com/3757314/205142774-9b878758-57c2-428a-92a0-d951252cfbbe.png">

<img width="1379" alt="screenshot_3" src="https://user-images.githubusercontent.com/3757314/205142794-c04f69c3-9e36-4157-829a-035c08d495d9.png">

<img width="663" alt="screenshot_4" src="https://user-images.githubusercontent.com/3757314/205142824-e7762d2b-9a5d-4eb6-b07e-e15a03c3670f.png">

**Comment by aricart** [comment]
Can you add something to the name like Date.now().   On the test I made with latest, the pending connections on Firefox are closed and only the current connection is closed.

**Comment by aricart** [comment]
@heikkilamarko you are absolutely right - if you wait a very long amount of time, the behavior is completely different. 


<img width="591" alt="image" src="https://user-images.githubusercontent.com/1032976/205198717-c1c25530-8a07-46b5-bb13-615bde1d8bfc.png">

The crazy thing is that, my handler can detect that it was closed - but it's like the API calls have no effect.

**Comment by heikkilamarko** [comment]
Yes. The problem only happens when you wait long enough. Sorry. I should have made this more clear in my comments. It's great that you can reproduce the problem now.

**Comment by heikkilamarko** [comment]
My current workaround/fix to this problem is to set the `timeout` property to a value greater than `1 minute`:

```js
const conn = await connect({
      servers: ["ws://localhost:9222"],
      name: "demo-ui",
      timeout: 120_000, // This fixes the problem
      maxReconnectAttempts: -1,
      waitOnFirstConnect: true,
    });
```

**Comment by aricart** [comment]
Yes I tried a number of things, and even pre-cancelling (which actually happens now) is not honored. Annotating that the WebSocket was cancelled also has no effect (tried to dispose it on create). The current workaround is what you have. While the Firefox folks are doing the right thing by the RFC, the bigger issue is that the client is not able to understand that this is the case or the throttling that is being imposed. One thought I had was to make a version of the reconnect jitter (which takes a function) that implements a similar exponential backoff. This is on my list to do.
