### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by 905868332** [nats-io/nats.ws#174]
![image](https://user-images.githubusercontent.com/29794128/204960009-482679df-454d-474e-a7fe-c8e978af03d0.png)

**Comment by aricart** [comment]
I am not sure what stack you are using, but your transpiler is selecting the wrong source and not understanding the package.json correctly (you may want to update)
The ESM version of the library - the websocket runtime supported by this lib is the W3C WebSocket, is the ES library which you can find in the `esm/nats.js` of the npm module.

**Comment by aricart** [comment]
Also if you are cloning the repo, likely it won't work correctly, I suggest you `npm install nats.ws`.

**Comment by h0jeZvgoxFepBQ2C** [comment]
We are using webpacker and had the same error, we solved it by let babel transpile it:

```javascript
# environment.js
