### ISSUE TITLE
invalid stream name - stream name cannot contain '.'

### ISSUE THREAD

**Issue by JalilArfaoui** [nats-io/nats.ws#181]
I've been using requests and subscriptions successfully and I'm now trying to fetch a stream :

```ts
      const codec = JSONCodec();
      const stream = nc.jetstream();

      const msg = await stream.pull('pub.system.log.>', 'me');

      const m = codec.decode(msg.data);

      console.log('stream: ', m);

      msg.ack();
```

But I'm getting 

```console
Uncaught (in promise) Error: invalid stream name - stream name cannot contain '.'
    validateName nats.js:787
    validateStreamName nats.js:779
    pull nats.js:8694
```

And I don't understand the error since stream names usually contain dots as seen in https://github.com/nats-io/nats.deno/blob/main/jetstream.md

Same error with

```ts
      const codec = JSONCodec();
      const stream = nc.jetstream();

      const msgs = await stream.fetch('pub.system.log.>', 'me');

      const done = (async () => {
        for await (const m of msgs) {
          const json = codec.decode(m.data);
          console.log('stream', json);
          m.ack();
        }
      })();
      await done;
````

**Comment by aricart** [comment]
@JalilArfaoui the API use above is wrong, the API there wants a stream name, not a subject, and it retrieves the next message for that durable consumer, streams indeed cannot have dots.

**Comment by JalilArfaoui** [comment]
Yes, I got confused, reading the documentation, with the others methods that use subject like `publish` or `pullSubscribe` …

It's working perfectly now.

**Comment by wenerme** [comment]
for pullSubscribe

> invalid stream name - stream name cannot contain :

nats can create stream with `:`, but nats.ws can not pullSubscribe
