### ISSUE TITLE
Issue with object store `put` using deno

### ISSUE THREAD

**Issue by jmordica** [nats-io/nats.ws#182]
Using:
deno 1.29.1
natsws 1.11.1

I'm having an issue when trying to `put()` like:
```js
import { connect } from "natsws";

function readableStreamFrom(data: Uint8Array): ReadableStream<Uint8Array> {
  return new ReadableStream<Uint8Array>({
    pull(controller) {
      // the readable stream adds data
      controller.enqueue(data);
      controller.close();
    },
  });
}

const nc = await connect({
  servers: "ws://127.0.0.1:8080",
  token: "secret"
});

const js = nc.jetstream();

const os = await js.views.os("mybucket");

const info = await os.put({
  name: "hello",
  description: "test",
}, readableStreamFrom(await Deno.readFile(`/path/to/my/file`)));
```

I get an error `TIMEOUT` almost every time. This particular file is 8mb in size. I can upload files < 1mb without an issue.

However, when I switch to the nats.deno module @ `https://deno.land/x/nats/src/mod.ts` and swap out my `servers` prop for `nats://127.0.0.1:4222` I can successfully `put()` my file every time without a timeout/error.

----

Another strange thing (could be related to the above) is that when using either `nats.deno` or `natsws` module, I'm not able to see metadata using nats cli: `nats object info mybucket hello` for objects uploaded by the module.
```
nats: error: nats: object not found
```

However, I can `nats object ls mybucket` and see the object list successfully.

Also, when putting objects via nats cli, I'm only able to `list()` objects and not retrieve their `info()` or `get()` via the `nats.deno` or `natsws` module.

I tried re-creating the buckets completely and that didn't seem to resolve anything.

Thanks for any help here.

**Comment by aricart** [comment]
@jmordica I am not able to reproduce the issue, perhaps more info is necessary.
I am not sure about versions and runtime 

I tried with both deno and browser - if you are trying with node, not sure what happens there since you need the correct transport and ES functionality.

https://gist.github.com/aricart/e20012b96747b04c564269629ac327ba

**Comment by aricart** [comment]
@jmordica I tried with 80mb and I see the issue. The publishes are requests - let me take a look

**Comment by jmordica** [comment]
Sweet!

**Comment by aricart** [comment]
@jmordica `npm install nats.ws@latest`!

**Comment by jmordica** [comment]
Awesome thanks!
