### ISSUE TITLE
What shall I do to support websocket?

### ISSUE THREAD

**Issue by kuange** [nats-io/nats.ws#19]
Nats.ws requires a nats-server with websocket support.

**Comment by kuange** [comment]
I saw this video https://www.youtube.com/watch?v=3PYFVN7dvxQ&feature=youtu.be
but websocket is unknown field

**Comment by kuange** [comment]
well, i saw this line:

well allmost, waiting for public server release...

**Comment by aricart** [comment]
@kuange - you can use this sandbox to pull a server and play with it. https://github.com/aricart/natsws-sandbox

**Comment by kuange** [comment]
@aricart thanks, and hope the websocket branch merge to master branch quickly.
