### ISSUE TITLE
[iOS12] SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.

### ISSUE THREAD

**Issue by toshi1127** [nats-io/nats.ws#190]
I get a runtime error on iOS12.
I think it is caused by the generated JavaScript code compiling to use a newer version, is there any way to resolve this?

![image](https://user-images.githubusercontent.com/32378535/224200636-10b19700-754d-40e9-a974-d2df25b13abd.png)

```
Browser: iOS12
nats.ws version: 1.14.0
```

**Comment by aricart** [comment]
possibly some issue with webpack? From the above I cannot tell any point in the library's code.

**Comment by aricart** [comment]
Can you try to figure out what the code is where that is?

**Comment by toshi1127** [comment]
@aricart Thanks for the reply!
A repository has been created in which the error is reproduced.
If I start the server with `yarn run dev` and open it in the iOS12 browser, the error occurs.

https://github.com/toshi1127/nats-ws-issues-190

<img width="444" alt="image" src="https://user-images.githubusercontent.com/32378535/224459576-bedd02b8-c212-4bee-8fdc-57cb291e9644.png">

**Comment by aricart** [comment]
@toshi1127 thank you for submitting the test setup - the url for the connect was wrong using something like `wss://demo.nats.io:8443` does the right thing.

I don't have the IOs simulator, but on ipad,iphone it works.

**Comment by aricart** [comment]
![PXL_20230315_164310043](https://user-images.githubusercontent.com/1032976/225381610-2602f764-9adf-49dc-9a60-1f8a52817eed.jpg)
![PXL_20230315_164629615](https://user-images.githubusercontent.com/1032976/225381653-facd3e7b-1d8b-4d66-8958-f524c251fd94.jpg)

**Comment by aricart** [comment]
Perhaps 12.8 (from 2018) is too old. My guess is that it doesn't support `?:` or nullish coalescing `??`. You may want to try and shim that for your application.

**Comment by aricart** [comment]
For the record, the device was an iPhone 6s Plus from 2015...
