### ISSUE TITLE
Nats.WS client crashes

### ISSUE THREAD

**Issue by efntallaris** [nats-io/nats.ws#197]
Hello,

I have been using nats.ws recently to connect to a nats server.

I have followed the necessary steps  to setup the config on the server side. The config looks like this.:

`port: 4222
max_payload: 52428800 # 50 MB i know its big but its for testing purposes, the payloads are not bigger than 10mbs

websocket: {

        tls:{

                  # Path to the TLS certificate file
                  cert_file: "/tls_keys/cert.pem"

                  # Path to the TLS key file
                  key_file: "/tls_keys/key.pem"
        }
        port: 4223
}`

I have been using a client which publishes big payloads on spescfic topic. This client connects on port 4222.

I have made another client in python from which I subscribe to this specific topic and I am receiving messages no problem. This client also connects on port 4222.

I have made the similar client from which I connect through nats.ws and try to receive the same messages. This client connects on port 4223 ( wss )

The problem is that the nats.ws client crashes after some time throwing this error on the nats.ws client:
![image](https://github.com/nats-io/nats.ws/assets/58358951/7d168553-7cdd-4089-82eb-f100ecad68d8)

and this is what I happens on the client side which is publishing:
![image](https://github.com/nats-io/nats.ws/assets/58358951/cc99da41-50bc-478d-bab2-fa45e74b3069)

If I am only using port 4222 ( 'raw' nats) to publish and subscribe no issues. If I connect nats.ws all clients are crashing (subscriber running on 4223 and also publisher running on 4222).

The nats.ws version I am using:
`"nats.ws": "^1.14.0",`

Nats version:

`Version:  2.9.16`

**Comment by aricart** [comment]
Are you running on node?
Can you attach a simple test case where I can reproduce?
Also have you looked into using multiple messages instead of what you are doing?

You can receive multiple messages with a single request if you use:
https://nats-io.github.io/nats.deno/interfaces/NatsConnection.html#requestMany

You are on your own for doing the initial split, but I would just do the sentinel request strategy - that is send end the send by publishing a single empty message.

Also - you can use JetStream to store and forward a large asset like that - with ObjectStore you would just put it in the store, and send the name of the asset to the client which can then retrieve it.

**Comment by aricart** [comment]
I wrote a little example for you to try out - you can use a ws connection, as the API is the same:

https://github.com/nats-io/nats.deno/blob/chunk-example/examples/services/03_bigdata.ts

https://github.com/nats-io/nats.deno/blob/chunk-example/examples/services/03_bigdata-client.ts

**Comment by aricart** [comment]
I verified with ws, and I am able to have the service send a 50MiB in single message with no issue on the client (using the examples above):
```javascript
import { connect, JSONCodec } from "../esm/nats.js";

const nc = await connect({servers: "ws://localhost:9222"});

const size = 50_000_000;

const start = performance.now();
const iter = await nc.requestMany(
    "data",
    JSONCodec().encode({ size }),
    {
        strategy: "sentinelMsg",
        maxWait: 10000,
    },
);

let received = 0;
let count = 0;
for await (const m of iter) {
    count++;
    received += m.data.length;
    if (m.data.length === 0) {
        // sentinel
        count--;
    }
}

console.log(performance.now() - start, "ms");

console.log(`received ${count} responses: ${received} bytes`);
await nc.close();
```

<img width="1307" alt="image" src="https://github.com/nats-io/nats.ws/assets/1032976/90a85ea9-8d17-443e-8fb3-04fb24f3e9ef">

**Comment by aricart** [comment]
The above is with  nats-server v2.9.17, running a config that allows the 50mb payload

**Comment by efntallaris** [comment]
Hello @aricart,

This version works for me too. 
Thanks !

**Comment by aricart** [comment]
@efntallaris so the issue was solved with server change?

**Comment by efntallaris** [comment]
@aricart Yes, I was using docker and just changed the version and now seems to be working perfect

**Comment by aricart** [comment]
Awesome.  Take a look at the example I made.  I think smaller payloads are possibly better. But you can always test
