### ISSUE TITLE
unexpected response from server: "!!! -ERR 'Authentication Timeout'␍␊"

### ISSUE THREAD

**Issue by nidi3** [nats-io/nats.ws#205]
From time to time we get an "unexpected response from server" Error and on the console there's the message "!!! -ERR 'Authentication Timeout'"

- What does this mean?
- How should this be handled?
- The application has no access to the message, so we currently cannot implement a special action depending on the message.

Thanks

**Comment by aricart** [comment]
@nidi3 That means that the client was presented with a connect, but didn't authenticated quickly enough

there could be several reasons for this:

- if you changed these values on the server, and there was some latency (note that if the tls handshake doesn't complete within this time but that is only applicable to clients that upgrade the connection - not the case if you are using nats.ws)
-  if you are using an authenticator and configured it using a function that is taking too long to return the credentials. 

If the client fails to connect, and you have reconnect enabled, the client should just attempt to reconnect

Can you show your client config options and also verify that the server doesn't have a timeout directive for authorization
The config could have something like this:
```
authorization: {
    timeout: 3
```

**Comment by nidi3** [comment]
Hi @aricart 

Thanks for the quick answer! 

Indeed, we have an authorization timeout set. We'll try to set it higher.

> If the client fails to connect, and you have reconnect enabled, the client should just attempt to reconnect

Not sure about this part. We have reconnect enabled in the ConnectionOptions, so nats.ws should attempt to reconnect automatically? It seems not to.
Or should the application repeat the call?

There are two possible errors: 
- error.message == "'Authentication Timeout'"
- error.message == "unexpected response from server" with more details only logged on the console in debug mode.

The first case we can handle in the application, for the second case we don't know what the unexpected response was.

**Comment by aricart** [comment]
@nidi3, I am hoping on your side, you are NOT using an `authenticator` function that is async.
With that said, if the client is not configured with the option `waitOnFirstConnect: true,` it will attempt to reconnect only a few times, after that the connection will close. Is that your experience?

**Comment by aricart** [comment]
@nidi3 really want to know what your connection options are for the client, and the timeout for the server.

**Comment by aricart** [comment]
@nidi3 thanks for finding this, fix should be in the next release

**Comment by nidi3** [comment]
Hi @aricart 
Thanks for the fix, looks interesting.
Indeed, we have `waitOnFirstConnect: false`, we'll try to see if setting it to true helps.
