### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by breakboyandre** [nats-io/nats.ws#21]
Hello! I'm trying to install package from npm and i'm getting an error. Here is my log:

# npm install nats.ws@next

npm ERR! code EJSONPARSE
npm ERR! file /var/www/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token } in JSON at position 265 while parsing near '...pack.config.js",
npm ERR! JSON.parse   },
npm ERR! JSON.parse   "dependencies"...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

My npm version is 6.14.5

What am i doing wrong?

**Comment by aricart** [comment]
Not sure what you are doing:
```
/tmp 
➜ mkdir wst

/tmp 
➜ cd wst 

/tmp/wst 
➜ npm init -y
Wrote to /private/tmp/wst/package.json:

{
  "name": "wst",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



/tmp/wst ⬢ v10.20.1 
➜ npm install nats.ws@next
npm WARN wst@1.0.0 No description
npm WARN wst@1.0.0 No repository field.

+ nats.ws@1.0.0-17
added 2 packages from 2 contributors and audited 2 packages in 0.583s
found 0 vulnerabilities


/tmp/wst ⬢ v10.20.1 
➜ head node_modules/nats.ws/nats.js
!function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?define([],e):"object"==typeof exports?exports.nats=e():t.nats=e()}(window,(function(){return function(t){var e={};function r(n){if(e[

```

I also have npm: '6.14.4'.

**Comment by breakboyandre** [comment]
I'm newbie with npm. You helped me a lot. Fixed this error by creating package.json. Thank you!
