### ISSUE TITLE
Support jetstream feature

### ISSUE THREAD

**Issue by pkgonan** [nats-io/nats.ws#213]
### What motivated this proposal?

We are paid customers. And we use nats.ws in our project. But nats.ws did not support jetstream feature. When we want to use jetstream api, we should change sdk from nats.ws to nats.dino. So, we want to use jetstream feature without nats.nino.

### What is the proposed change?

Support jetstream feature in nats.ws.

### Who benefits from this change?

Synadia`s customers.

**Comment by aricart** [comment]
@pkgonan nats.ws indeed supports jetstream in nats.ws - the nats.deno library is the home for all the common code for the nats javascript clients. The nats.ws simply contributes the websocket transport. But all usage is the same.

https://github.com/nats-io/nats.ws#jetstream
```
const nc = await connect();
const js = nc.jetstream()
```

**Comment by aricart** [comment]
You can also see the basic sanity tests here:
https://github.com/nats-io/nats.ws/blob/main/test/jetstream.js

While the extensive tests live in the github.com/nats-io/nats.deno repo
