### ISSUE TITLE
Is it possible to stream with webrtc with nats.ws at the moment?

### ISSUE THREAD

**Issue by subhendukundu** [nats-io/nats.ws#22]
I was looking at this video https://www.youtube.com/watch?v=3PYFVN7dvxQ Amazing.
And I got curious to know how it was implemented. I saw wss is been implemented already on this repo.
Question is, will it be possible to stream multiple users using `nats.ws` out of the box methods?
Or we need to write custom methods for this? It would be great if there is any docs related to this.

Thanks

**Comment by aricart** [comment]
@subhendukundu if I understand correctly, you should be able to create multiple connections with different users from the same session. A session is really a single nats client, and they are all independent. Let me know if this doesn't answer your questions.

**Comment by subhendukundu** [comment]
I think I get the idea I guess, a total newbie to the whole concept. Few more silly question,
1. Do we have a performance testing document? I mean how many users can join in the same session?
2. How much core does it use in a session in any cloud provider?
3. Did you guys try making a video calling app using nats? I am planning to try out one.

**Comment by aricart** [comment]
@subhendukundu nats.ws is simply a client to [NATS](https://www.nats.io). NATS is a simple, secure, and performant communication platform with many different client language implementations. The [nats-server](https://github.com/nats-io/nats-server) is extremely efficient and performant, in a simple laptop, you can expect anywhere from 6-12 million messages per second depending on the payload size.

Take a look at our [docs](https://docs.nats.io), and see how you can use NATS!

**Comment by subhendukundu** [comment]
Thank you again for answering all my questions. You are amazing. :)
One last question if I may, I am planning on making an open-source video conferencing app (which definitely gonna show the potential of NATS, also with [Flutter](https://flutter.dev/) ), would you say this is very much possible with NATS and recommend to use NATS as I can add end to end encryptions very easily? 
If this has been done before with NATS, I would love to have some references if you can.

**Comment by aricart** [comment]
Nats as a transport would be super awesome. The challenge is actually the image processing side...
