### ISSUE TITLE
Timeout while connecting through react native (Specifically Android, for iOS it is working)

### ISSUE THREAD

**Issue by trader2b-dev** [nats-io/nats.ws#220]
### What version were you using?

Server Version: 2.8.4
Client Version: 1.11.2 - nats.ws (nats.js file is being used)

### What environment was the server running in?

The client is running on android (tried both, the emulator and the actual device)

### Is this defect reproducible?

 `
connect({
        servers: server, //My Server URL i.e. wss://url.to.server/ws
        noEcho: true,
        token: sdjfhjsERDFDf, //A String is being used here
      })
        .then((nc: NatsConnectionImpl) => {
          resolve(nc);
        })
        .catch((reason) => {
          console.log("REASON>>>", reason);
          resolve(null);
        })
    });
`

### Given the capability you are leveraging, describe your expectation?

This should connect to the web socket and not give the timeout as it is running for the iOS version with the same code mentioned above.

### Given the expectation, what is the defect you are observing?

For Android devices, I am getting connection timeout while it is working fine for iOS.

**Comment by talesborn** [comment]
I'm facing the same problem here.

**Comment by the-murer** [comment]
Same problem here

**Comment by aricart** [comment]
Are you setting the timeout? - The timeout means that the client was not able to get a handshake within the specified timeout window - by default it is 20s.

**Comment by aricart** [comment]
There's a duplicate, that has some additional information:

https://github.com/nats-io/nats.ws/issues/221

**Comment by talesborn** [comment]
NATS seems to take a while to connect, and sometimes it doesn’t connect at all. From my experience, it takes significantly longer to connect on Android—sometimes over a minute.

On iOS, however, the connection time is much shorter, being noticeably faster than on Android, even when using the same network.

Also, depending on the version of Android, the connection time appears to increase further.

This is how I’m making the connection. When I get a timeout, I have to try reconnecting

```
export async function createConnection(
  localId: string,
  userId: string,
  authenticator: string,
) {
  try {
    const server: string[] = ['wss://serverhost'];
    const clientId: string = `${localId}-${userId}-${
      Math.floor(Math.random() * 100) + 1
    }`;
    const connection: NatsConnection = await connect({
      name: clientId,
      servers: server,
      authenticator: credsAuthenticator(
        new TextEncoder().encode(authenticator),
      ),
      tls: null,
      debug: false,
      noEcho: true,
      inboxPrefix: `${localId}._INBOX`,
      timeout: 3000,
      reconnect: true,
    });
    console.log('NATS CONNECTED');
    return new BrokerClient(clientId, connection);
  } catch (exception) {
    console.error(exception);
    return null;
  }
}
```

**Comment by talesborn** [comment]
> Você está definindo o tempo limite? - O tempo limite significa que o cliente não conseguiu obter um handshake dentro da janela de tempo limite especificada - por padrão, é 20s.


NATS seems to take a while to connect, and sometimes it doesn’t connect at all. From my experience, it takes significantly longer to connect on Android—sometimes over a minute.

On iOS, however, the connection time is much shorter, being noticeably faster than on Android, even when using the same network.

Also, depending on the version of Android, the connection time appears to increase further.

This is how I’m making the connection. When I get a timeout, I have to try reconnecting

export async function createConnection(
  localId: string,
  userId: string,
  authenticator: string,
) {
  try {
    const server: string[] = ['wss://serverhost'];
    const clientId: string = `${localId}-${userId}-${
      Math.floor(Math.random() * 100) + 1
    }`;
    const connection: NatsConnection = await connect({
      name: clientId,
      servers: server,
      authenticator: credsAuthenticator(
        new TextEncoder().encode(authenticator),
      ),
      tls: null,
      debug: false,
      noEcho: true,
      inboxPrefix: `${localId}._INBOX`,
      timeout: 3000,
      reconnect: true,
    });
    console.log('NATS CONNECTED');
    return new BrokerClient(clientId, connection);
  } catch (exception) {
    console.error(exception);
    return null;
  }
}

**Comment by talesborn** [comment]
> Você está definindo o tempo limite? - O tempo limite significa que o cliente não conseguiu obter um handshake dentro da janela de tempo limite especificada - por padrão, é 20s.


NATS seems to take a while to connect, and sometimes it doesn’t connect at all. From my experience, it takes significantly longer to connect on Android—sometimes over a minute.

On iOS, however, the connection time is much shorter, being noticeably faster than on Android, even when using the same network.

Also, depending on the version of Android, the connection time appears to increase further.

This is how I’m making the connection. When I get a timeout, I have to try reconnecting

```
export async function createConnection(
  localId: string,
  userId: string,
  authenticator: string,
) {
  try {
    const server: string[] = ['wss://serverhost'];
    const clientId: string = `${localId}-${userId}-${
      Math.floor(Math.random() * 100) + 1
    }`;
    const connection: NatsConnection = await connect({
      name: clientId,
      servers: server,
      authenticator: credsAuthenticator(
        new TextEncoder().encode(authenticator),
      ),
      tls: null,
      debug: false,
      noEcho: true,
      inboxPrefix: `${localId}._INBOX`,
      timeout: 3000,
      reconnect: true,
    });
    console.log('NATS CONNECTED');
    return new BrokerClient(clientId, connection);
  } catch (exception) {
    console.error(exception);
    return null;
  }
}
```

**Comment by talesborn** [comment]
> Há uma duplicata que contém algumas informações adicionais:
> 
> #221

I tried this, but the connection is still either slow or not connecting at all.
