### ISSUE TITLE
WebSocket connection to 'wss://localhost:9222/' failed: Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by ChenYida** [nats-io/nats.ws#23]
I've generated cert and key pem file by using mkcert.
Then I run the following command:
nats-server --tls --tlscert=server-cert.pem --tlskey=server-key.pem -ms 9222
The server started correctly. (Starting https monitor on 0.0.0.0:9222, Listening for client connections on 0.0.0.0:4222 Server is ready)
But when I ran the nats.ws samples, I got the following error:
transport.ts:76 WebSocket connection to 'wss://localhost:9222/' failed: Error during WebSocket handshake: Unexpected response code: 200
Am I doing anything wrong? How can I solve this issue? Hope you can help!

**Comment by ChenYida** [comment]
Besides, the conf file is not working. It told me that "Unknown field: Websocket". I use the latest natserver v2.1.7.

**Comment by mheers** [comment]
I think Websockets will be available in the next release natsserver v2.1.8 so you need to start the server from the current master branch.

**Comment by ChenYida** [comment]
> I think Websockets will be available in the next release natsserver v2.1.8 so you need to start the server from the current master branch.

Thank you so much! I compiled the nats server master branch and it worked!

**Comment by ripienaar** [comment]
We also publish nightly docker releases which includes this already.  `synadia/nats-server:nightly`

**Comment by kozlovic** [comment]
@ChenYida You cannot configure the websocket listen specification from command line. What you did was actually to configure the HTTPs monitoring endpoint, so when you pointed your websocket client to that port, you got a HTTP 200 status code.
As explained by others, the Websocket support in the NATS Server is already available in the main branch, but not as part of an official release yet. That is, the latest NATS v2.1.7 does not have Websocket support.
