### ISSUE TITLE
How i can use ObjectStore if is the interface?

### ISSUE THREAD

**Issue by sheldygg** [nats-io/nats.ws#236]
### Observed behavior

ObjectStore is the interface

### Expected behavior

In this [issue](https://github.com/nats-io/nats.ws/issues/234#issuecomment-2070927960) you say what I must use ObjectStore

### Server and client version

-

**Comment by aricart** [comment]
You can take a look at the jetstream documentation here:
https://github.com/nats-io/nats.ws?tab=readme-ov-file#jetstream

From there, you can see the ObjectStore section.
https://github.com/nats-io/nats.deno/blob/main/jetstream.md#objectstore

**Comment by aricart** [comment]
Just to give you a mental map, it all starts with the NatsConnection - there, there's the `jetstream()` call which will have a `views` property, which also has an `os` property which lets you access/create an ObjectStore. Very soon now, the JetStream functionality will be split and that will centralize the documentation depending on what you are exploring.
