### ISSUE TITLE
Get error using nats.ws and angular 17

### ISSUE THREAD

**Issue by fclmman** [nats-io/nats.ws#241]
### Observed behavior

get error building project
Could not resolve "crypto"

    node_modules/nats.ws/esm/nats.js:4913:24:
      4913 │       crypto1 = require('crypto');
           ╵                         ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

### Expected behavior

project builds without error

### Server and client version

 "nats.ws": "^1.26.0",
 "@angular": "^17.3.0",

### Steps to reproduce

create project with ng new, add nats.ws create connection and try to build

**Comment by aricart** [comment]
You may want to extract the "node_modules/nats.ws/esm/nats.js" file and reference it directly - depending on your bundler it may not correctly select between cjs and esm.

**Comment by aricart** [comment]
@nickchomey bundle is now an external api, it is still supported - with that said, I am in the middle of an extensive refactoring for the clients, which will split the lib into several - core, jetstream, kv, object store and services. Each will have an esm only option or a node option - the ESM only (via jsr) will do exactly what you want as it will only involve webapis.

**Comment by playerx** [comment]
Hi guys, still having the same issue with Angular 18:
```
✘ [ERROR] Could not resolve "crypto"

    node_modules/nats.ws/esm/nats.js:4911:24:
      4911 │       crypto1 = require('crypto');
```

@nickchomey can you share the forked version please? Or maybe there is other solution? 

@aricart I checked, but didn't find nats.ws on jsr, can you share if it's there? maybe with other name?

thanks 🙌🏻

**Comment by aricart** [comment]
The esm lib shouldn't have a require, as that is not available in browser, so all browser apps would fail. Shims for crypto should be available on npm...

**Comment by playerx** [comment]
@aricart Yes I agree, I think issue is that nats.ws loads crypto.

I've created a simple project to reproduce the issue:
https://github.com/playerx/nats-issue

Steps I did:
1. Create a new angular with `ng new` command
2. Install and use `nats.ws` by running: `npm i nats.ws`

And `npm run build` fails with the error I mentioned.

If there is a way to avoid loading `crypto` please let me know.

**Comment by playerx** [comment]
Not sure if installing shim is the right way to go. I think the main problem is that it loads crypto when it shouldn't.

**Comment by playerx** [comment]
Adding the following in package.json did the trick:
```
"browser": {
    "crypto": false
  }
 ```
 
 However, I think for the long-term solution nats.ws shoudn't be loading `crypto` in browser.

**Comment by aricart** [comment]
Crypto is required for objects tore, and works perfectly in browser... 

https://developer.mozilla.org/en-US/docs/Web/API/Crypto

**Comment by aricart** [comment]
The 3.0 version of the clients breaks the lib into several. Crypto dependency will be on the objectstore module only
 Stay tuned

**Comment by jymukendi** [comment]
Hi guys, I am also getting the same issue in the latest Angular 18. `ng build` is throwing the same error:
![Screenshot 2024-10-16 at 08 50 47](https://github.com/user-attachments/assets/fcf63cf2-ec3e-456c-ae21-6775d2e283a0)

@playerx's workaround got rid of it, but that should get fixed in nats.ws.
