### ISSUE TITLE
bindOnly on KV prevents read messages from KV

### ISSUE THREAD

**Issue by VRedondo** [nats-io/nats.ws#243]
### Observed behavior

When I try to get a KV using the `bindOnly` option to avoid the KV creation in case it's not present, 
when I try to get the messages from it it throws an exception indicating there's a jetstream that matches the search subject 

```ts
const kvStore = await conn.jetstream().views.kv(kvName, { bindOnly: true });
const messages = await kvStore.watch();
```

### Expected behavior

It should let get the messages from the KV if it exists in the nats-server

### Server and client version

nats-server image: nats:2.10.10-alpine
nats.ws: 1.19.1

### Steps to reproduce

1. create a KV in the nats-server
2. try to consume the messages in it using the watch instruction

**Comment by aricart** [comment]
this works for me?

```javascript
  const js = nc.jetstream();
  let kv = await js.views.kv("A");
  await kv.put("A", "a");

  kv = await js.views.kv("A", {bindOnly: true});
  (async () => {
    for await(const e of await kv.watch()) {
      console.log(e.key)
    }
  })().catch()
```

**Comment by aricart** [comment]
Also - make sure you are current in your client release.

**Comment by VRedondo** [comment]
you're right @aricart , upgrade to the latest version fixs the issue, thanks!

**Comment by VRedondo** [comment]
Sorry the error seems to be as well in the latest version, it only happens if you try to read an existing KV for instance

Steps
1. Create the KV in the server, in my case, I'm creating a mirror KV 
2. Try to read the KV using the ws client with the `{ bindOnly: true }` 

Current result:
No messages are getting returned
