### ISSUE TITLE
Nats WS Socket Converting raw bytes to object

### ISSUE THREAD

**Issue by pbower** [nats-io/nats.ws#248]
### Observed behavior

Hi there,

Awesome library. However, I am observing the strangest behaviour, and I thought I was going crazy until I've definitely logged and tested to confirm that the issue is not on either side. When I send serialised flatbuffer data over the nats web socket in bytes, by the time it's in the nats channel, and when it's received on the other end, it's in the format of the object, rather than the bytes.

Is there a step in the process that serialises/deserialises the data, as what I'm experiencing looks similar to [this issue](https://github.com/unjs/crossws/issues/37) ?

Nats message example:

`nats sub -s ws://localhost:9584 myService.getMyData`
>22:14:29 Subscribing on myService.getMyData 
>
> [#1] Received on "myService.getMyData" with reply "_INBOX.UXZPK5VNKI6SZH4GYCTBP1.UXZPK5VNKI6SZH4GYCTBIP"
> 
> 
> 
> 4
> 
> 	Monster
> 
> 	
> 
> 
> 'd
> 
> 

That's after first client initiates (onto the websocket) via :

                const request: Uint8Array = initialiseFlatbufferDataRequest(my_number_range, monster_number, monster_name);
                ({ monsterPackage, error, loading } = await ServiceAccessor.monsterService.getMonsterFromServerNats(request, 'monsterService.getMonsterFromServerNats'));
                
Then, by the time it is 'immediately' received in python, it can't process it because it's already serialised as the flatbuffer object rather than the bytes, but in a slightly malformed way.

`logger.debug(f"GetMonsterFromServer: Received request to get Monster from server: {str(request)}")`

> app-server-1  | 2024-07-03 11:27:16,810 - DEBUG - GetMonsterFromServer: Received request to get monster from server: <serialisation.flatbuffer.MonsterService.MonsterBatch.MonsterBatch object at 0x751564e8e5c0>

Whereas, the above should simply be a bytes payload from my understanding.

However, if my understanding is incorrect and I'm missing something fundamental please  let me know.

Thanks for your help.

### Expected behavior

The raw byte are what's transmitted over the nats channel, 

### Server and client version

Nats server version 2.9.25
nats.ws@1.29.0

### Host environment

Ubuntu 24.04
Google Flatbuffers v24.3.25
Data from Typescript to Python

### Steps to reproduce

1. Serialise a flatbuffers object client-side to bytes https://flatbuffers.dev/flatbuffers_guide_tutorial.html
2. Send the bytes over the NATS.ws via a websocket.
3. Upon receiving from the nats client that receives the message payload, it is the string object rather than the bytes.

**Comment by aricart** [comment]
This is an issue for nats cli or the go client, but in nats cli, you can also try the `--raw` option that will send the data provided you can capture it to a file.

**Comment by aricart** [comment]
@pbower If the `--raw` option didn't solve your issue, please open an issue in https://github.com/nats-io/natscli explaining your use case.
