### ISSUE TITLE
types declaration not getting bundled in node package.

### ISSUE THREAD

**Issue by aricart** [nats-io/nats.ws#26]

**Comment by mheers** [comment]
I'm playing around with the beta (I have the @next working). Do you have a workaround for this issue as I'm not able to include it yet:
`Cannot find module 'nats.ws/nats.mjs' or its corresponding type declarations.`

**Comment by aricart** [comment]
@mheers nats.ws@beta2 provides the typescript declaration.

Note that it also changes the client APIs, so several modifications to your code will be required.

**Comment by mheers** [comment]
Thank you very much for providing the type declaration. It seems as if `connect` is not yet in the declarations.
