### ISSUE TITLE
possible to support just ws instead wss

### ISSUE THREAD

**Issue by mrudangit** [nats-io/nats.ws#29]
Regular ws:// support would be great e.g. in Intra-Net environments e.g. Electron apps etc can connect to NATS 
via ws:// , for apps that are streaming lots of data it will be more performant than wss

**Comment by kozlovic** [comment]
This is a restriction put in the NATS Server, not the client library. The reason we force TLS is because WS clients are expected, or likely, to use bearer tokens, and without TLS is would be "easy" to steal them.

**Comment by mrudangit** [comment]
Agree, yes you have to configure with websocket block and provide TLS info , however in close corporate intranet e.g. in one of the use case i am trying out is publish real time market data to HTML5 apps running under Electron. e.g. volume is 1k msg size per record 1000 records and each record update 4 times per second. 
WSS will spend considerable time in decrypting

**Comment by kozlovic** [comment]
Understood. My point is that the server is forcing use of TLS. Please create an issue against NATS Serve (https://github.com/nats-io/nats-server) asking to support non TLS websocket configuration, maybe with a flag such as "insecure: true" in the websocket config block to bypass the TLS requirement?

**Comment by mrudangit** [comment]
sounds good. 
Thanks

**Comment by aricart** [comment]
I have updated the client to support WS connections. However, the support is in the current development version of the client, which means that it will affect any code you might have written.

To connect to `ws://`, the new client offers the `ws` option: `{ws: true}` will allow the client to connect to non-wss server..
