### ISSUE TITLE
Remove warning from nats.mjs

### ISSUE THREAD

**Issue by ChenYida** [nats-io/nats.ws#34]
Hi, I'm using React js. I import { connect, StringCodec } from "nats.ws", and then I get the following warning when start npm and also in chrome:

**Compiled with warnings.

./node_modules/nats.ws/nats.mjs
Critical dependency: the request of a dependency is an expression**

Can you find out some ways to solve this issue?

**Comment by aricart** [comment]
what version are you using do you know?

**Comment by aricart** [comment]
can you do the following:

```bash
# clone the nats.ws repository:
git clone https://github.com/nats-io/nats.ws.git

# install [deno](https://deno.land):
npm run setup

# build the library
npm run build

# install the master of nats-server, if you have 
# [Go](https://golang.org/doc/install) installed,
# you can easily clone and build the latest from
# master:
npm run install-ns

# start the built nats-server:
npm run start-nats

# start an http server to serve the content in
# the examples directory:
npm run start-http

# point your browser to: http://localhost:4507/examples
# click on one of the HTML files
```

Open any of the examples (chat.html, bench.html, etc) - I don't see any warnings on my side.

**Comment by aricart** [comment]
Also. - what OS are you running.

**Comment by ChenYida** [comment]
Windows OS, Nats ws 1.0.0-90. Chrome.  Nats server is built using nats server main branch.
The cmd is not vaild for windows (SH is not a valid command), so I cannot using your script.
Recently I see the  Nats ws has changed a lot, so I tried to integrate into our project.

I change **import * as nats from "nats.ws";** to **import { connect, StringCodec } from "nats.ws";**
and also some publish and subscribe areas. But I got the warning from browser. It seems the warning is from **node_modules\react-dev-utils\webpackHotDevClient.js** saying **./node_modules/nats.ws/nats.mjs
Critical dependency: the request of a dependency is an expression**. Anyway, it is not important.

Besides, I create a new project using create react app template(**npx create-react-app my-app**). And I added **npm install nats.ws@beta2** and add <import { connect, StringCodec } from "nats.ws";> in app.js. And it failed to compile.
Here is the error:
**./node_modules/nats.ws/nats.mjs 605:35
Module parse failed: Unexpected token (605:35)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|                 const a = mh.values(k);
| 
>                 if (v.length !== a?.length) {
|                   return false;
|                 }**
Could you help if you have time?

**Comment by aricart** [comment]
@ChenYida - so the ws library is packaged as an ES Module, so if you try to do an import into some node-based project, it is going going to work, however, if you did the same import into browser application, the import should be just fine provided that you are loading your script like this:

```
<script type="module">
  // load the library
  import { connect } from './nats.mjs'
  // do something with it...
</script>
```

Note `type="module"`.

**Comment by aricart** [comment]
You may have to tweak your babel configuration to specify that the nats.mjs library is `ES Module`. I don't use babel, so I cannot help you in that transpilation step.

**Comment by ChenYida** [comment]
Thanks aricart! Finally I find some ways to solve this issue.

**Comment by onichandame** [comment]
> Thanks aricart! Finally I find some ways to solve this issue.

I am seeing the exact warning. Could you kindly share how it was solved?

**Comment by ChenYida** [comment]
> > Thanks aricart! Finally I find some ways to solve this issue.
> 
> I am seeing the exact warning. Could you kindly share how it was solved?

Just ignore it.
