### ISSUE TITLE
When library will be production ready ?

### ISSUE THREAD

**Issue by dmitrydiavita** [nats-io/nats.ws#39]
Hi, we are planning to integrate with nats by websockets and want to use this library, can you suggest when it will be ready for production usage ?

**Comment by aricart** [comment]
The library is ready - awaiting for the server to release. 

Until the server releases there's a possibility that the API could have very small modifications as works on the JetStream wrappers are in progress and may introduce slight changes to allow for a better experience on JetStream. With that said, if you are running your nightly/self-built server you should be OK. Just make sure to clamp on versions and upgrade only after understanding the updates by looking at the commit logs - semver won't be enforced until after the server releases.

One thing that will be changing is how to specify `ws://` support, right now it has a custom property that probably will be folded with the `tls` option that already exists.
