### ISSUE TITLE
How to properly connect by WebSocket using JWT

### ISSUE THREAD

**Issue by dmitrydiavita** [nats-io/nats.ws#50]
Hi , in case of connecting with go client library using JWT credentials it would be like in example https://github.com/nats-io/nats.go#new-authentication-nkeys-and-user-credentials
Can you please give an example of how properly configure WebSocket connection with JWT and nkey ?

**Comment by aricart** [comment]
@dmitrydiavita thanks for the issue, I updated the readme for the source project:

https://github.com/nats-io/nats.deno#authenticators
