### ISSUE TITLE
Deno bundler is broken on Deno versions better than 1.4.6

### ISSUE THREAD

**Issue by mheers** [nats-io/nats.ws#52]
Building the *nats.mjs* seems broken. It double declares `render1`:

Line 5042: `const render1 = render2;`
Line 5968: `const render1 = render;`

Also the jwtAuthenticator (which is exported correctly in *nats.d.ts*) is not accessible when importing: `"export 'jwtAuthenticator' was not found in 'nats.ws'`.

**Comment by aricart** [comment]
with deno 1.5.0 I can reproduce the issue. For now, `deno upgrade --version 1.4.2` to get a working build.

**Comment by aricart** [comment]
You can also `npm install nats.ws` and get the currently released version.

**Comment by mheers** [comment]
Thank you very much for your fast and helpful response. I can confirm, that it works with deno 1.4.2.

Just having `npm install nats.ws` is unfortunately not possible for me because it's missing the `nats.mjs` which I need to import it into my Vuejs application.

For now I simply adjusted the `package.json` with the script: `"build": "deno upgrade --version 1.4.2 && deno run --allow-all --unstable --reload src/mod.ts && deno bundle --unstable src/mod.ts ./nats.mjs"`

**Comment by aricart** [comment]
Yes the bundler on deno 1.5.0 has a lot of issues filed. I just added another 

https://github.com/denoland/deno/issues/8188

**Comment by aricart** [comment]
https://github.com/denoland/deno/issues/8246 - bundler is still broken as of 1.5.3

**Comment by aricart** [comment]
https://github.com/denoland/deno/issues/8481 - bundler is still broken as 1.5.4

**Comment by aricart** [comment]
As of deno 1.6.0 the bundler is still broken
https://github.com/denoland/deno/issues/8725

**Comment by aricart** [comment]
deno version 1.7.4 seems to be working fine.
