### ISSUE TITLE
Error connecting to NATS: ReferenceError: setUrlParseFn is not defined

### ISSUE THREAD

**Issue by delaneyj** [nats-io/nats.ws#55]
Trying to build per README instructions but all examples give the error `Error connecting to NATS: ReferenceError: setUrlParseFn is not defined`

**Comment by aricart** [comment]
This is a bundling issue - the current deno bundler is broken, downgrade deno.
`deno upgrade --version 1.4.6` should do the trick.

**Comment by aricart** [comment]
See the on going issue - https://github.com/nats-io/nats.ws/issues/52
