### ISSUE TITLE
Which recent NATS server supports websockets?

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats.ws#56]
Hi,
I am trying to find a version of nats-server with websocket support. 
Even the latest version 2.1.9 does not support the configuration option "websocket".

**Comment by kozlovic** [comment]
The websocket support in the NATS Server is in the main branch and available on nightly builds (`docker pull synadia/nats-server:nightly`). The next public release planned for mid/end of this month (Dec 2020) will have official support for Websocket, MQTT and JetStream.
