### ISSUE TITLE
error callback?

### ISSUE THREAD

**Issue by delaneyj** [nats-io/nats.ws#58]
https://github.com/nats-io/nats.js/issues/130 has a git using `conn.on('error', err=>...` but there doesn't appear to be a similar option in nats.ws.  I want to notify the in the client that a publish was unsuccessfully due to authorization failure.

**Comment by aricart** [comment]
If you get a runtime error such as a permission error, the connection will eventually terminate. If it is a subscription error, the subscription iterator (or handler if you set one) will show the error to give a closer association to where the failure was.

For a publish conn.closed() will have the error you are looking for.
