### ISSUE TITLE
Webpack warning

### ISSUE THREAD

**Issue by delaneyj** [nats-io/nats.ws#59]
When using in a Webpack project via `import {connect} from 'nats.ws'`  get this 
```ts
WARNING in ./node_modules/nats.ws/nats.mjs 34:35-46
Critical dependency: the request of a dependency is an expression
```
Although it does work raising in case it's a long term issue.

**Comment by aricart** [comment]
We consume the bundle project from deno as it works for browsers as it is. If you have more specific bundling requirements it may require a different process - such as cloning the nats.deno project and doing a build via tsc.

I have already done the heavy lifting on the nats.js side (as some of the imports have to be re-written). But that may give you an alternative. See https://github.com/nats-io/nats.js/blob/nd/package.json

**Comment by delaneyj** [comment]
If anyone else runs into this it can be solve via ` new ContextReplacementPlugin(/nats.ws/)` being added to your webpack plugins.

**Comment by aricart** [comment]
Thanks for the hint.!
