### ISSUE TITLE
different version of deno has different errors

### ISSUE THREAD

**Issue by MaloneGod** [nats-io/nats.ws#62]
Sorry, I am not an expert of js and can't solve these problems. Could you tell me which version do you use?

[nats.mjs.zip](https://github.com/nats-io/nats.ws/files/5767761/nats.mjs.zip)
For 1.5.3
The requested module '../nats.mjs' does not provide an export named 'Bench'/ 'JSONCodec'
For 1.5.4
Uncaught (in promise) ReferenceError: setUrlParseFn is not defined
    at connect2 (nats.mjs:3951)
    at Object.run (bench.js:55)
    at HTMLButtonElement.onclick (bench.html:46)

For 1.6.*
error: TS2794 [ERROR]: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
        resolve();
        ~~~~~~~~~
    at https://raw.githubusercontent.com/nats-io/nats.deno/v1.0.0-12/nats-base-client/util.ts:110:9

    An argument for 'value' was not provided.
        new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~
        at asset:///lib.es2015.promise.d.ts:33:34

TS2794 [ERROR]: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
        resolve();
        ~~~~~~~~~
    at https://raw.githubusercontent.com/nats-io/nats.deno/v1.0.0-12/nats-base-client/util.ts:116:9

    An argument for 'value' was not provided.
        new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~
        at asset:///lib.es2015.promise.d.ts:33:34

TS2345 [ERROR]: Argument of type 'T | undefined' is not assignable to parameter of type 'T | PromiseLike<T>'.
  Type 'undefined' is not assignable to type 'T | PromiseLike<T>'.
      resolve(value);
              ~~~~~
    at https://raw.githubusercontent.com/nats-io/nats.deno/v1.0.0-12/nats-base-client/util.ts:163:15

**Comment by MaloneGod** [comment]
I found you use 1.4.6 in another issue. Now it works.

**Comment by aricart** [comment]
This is still related to https://github.com/nats-io/nats.ws/issues/52
