### ISSUE TITLE
Provide async authenticator for connect

### ISSUE THREAD

**Issue by cuddlecake** [nats-io/nats.ws#69]
Hi there,

In our browser based use case, we use a JWT to authenticate with NATS.
With nats.ws version 1.0.0-117, it is possible to provide an `authenticator` like this: `() => ({ jwt: token })`

What we would like to do is to return a Promise instead of a plain object, because our access to the token is Promise-based, in case the token needs to be fetched.

With the current implementation, we would need to eagerly request a token and set it in a closure so that we can provide it synchronously in the callback, but this is prone to volatile errors.

**Comment by aricart** [comment]
While this sounds like a good idea, it creates a number of ripples that potentially could create a number of other issues, as the authentication path is subject to delays that won't be supported during the connection sequence - as expected response from the `INFO` protocol is time-sensitive.

While the connection process is asynchronous, you are aware of when this happens and can easily delay your connection until you have retrieved the necessary credentials.
