### ISSUE TITLE
Connection to Nats Client Parsing Error

### ISSUE THREAD

**Issue by gutrix** [nats-io/nats.ws#82]
Hi, I doubt this is an issue with nats.ws but I figured this is the best place to ask for help.

I have been able to successfully connect to my NATs server via C client, but I'm having trouble using NATs.ws for my client side.

Client Side Code:
```
import {connect} from 'nats.ws';
connect({servers: ['ws://localhost:4222']}).then(
    nats => {
        const sub = nats.subscribe('test');
        sub.callback = (_err, msg) => {
            console.log(msg);
        };
    }
);
```

Client Side Error:
```
VM10:1 WebSocket connection to 'ws://localhost:4222/' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONS
```

The error message I get from NATs:
```
[32028] 2021/02/18 16:42:04.527978 [←[31mERR←[0m] [::1]:51403 - cid:15 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: localhost:"...'
```

I'm quite new to HTTP and Websockets, but this seems like a pretty trivial thing to be caught up on.

**Comment by ripienaar** [comment]
The websocket connections go to a different port and require the port to be configured. At present the configuration is only in the master branch or our nightly docker builds

**Comment by kozlovic** [comment]
@curioustolearn In the websocket{} block. See documentation: https://docs.nats.io/nats-server/configuration/websocket/websocket_conf

So something like that:
```
listen: 127.0.0.1:4222

websocket {
    port: <your chosen port>
    no_tls: true,
}
```

Note that the feature is now GA in the latest release 2.2.0: https://github.com/nats-io/nats-server/releases/tag/v2.2.0

**Comment by curioustolearn** [comment]
@kozlovic Thank you so much! This worked great. This is such an incredible feature. I don't know any NATS, but have been looking to add real time to my webapp. I think NATS will be a great way to do it now. I have some other questions, but I will look for where the NATS community asks and answers questions. Thank you.

**Comment by kozlovic** [comment]
@curioustolearn You are welcome. If you did not join our Slack community, I would recommend you do so. There are tons of people that would be able to help with some of your questions. 
Here is our community page: https://nats.io/community/
And direct link to join Slack: https://natsio.slack.com/join/shared_invite/zt-41e6tnmb-qCt63606MKR1YxIHZf4ICA#/shared-invite/email

**Comment by curioustolearn** [comment]
Thank you. I have joined the slack nats.io community. Looking forward to using it.
