### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by jaredgreener** [nats-io/nats.ws#88]
I am implementing into a ReactJS app and unable to make a basic connection. Steps taken:

1) npm install nats.ws
2) import {connect, JSONCodec} from "nats.ws";
3) in my componentDidMount function:

```javascript
        const codec = JSONCodec();
        const natsClient = await connect(
            {
                servers: ["nats.invictme.com:4222"],
            },
        );
        const subscription = natsClient.subscribe("document."+this.state.documentID);
        await (async (subscription) => {
            for await (const m of subscription){
                subscription.getProcessed();
                let jsonData = codec.decode(m.data);
                this.serverMessageReceived(jsonData);
            }
        })(subscription);
```

./node_modules/nats.ws/nats.mjs 3499:17
Module parse failed: Unexpected token (3499:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| function defaultJsOptions(opts4) {
>   opts4 = opts4 ?? {};
|   return extend1({
|     apiPrefix: defaultPrefix,

<img width="572" alt="Screen Shot 2021-03-19 at 10 43 58 AM" src="https://user-images.githubusercontent.com/2931865/111806548-172e7e80-88a0-11eb-8db1-93b2a59926b5.png">

**Comment by aricart** [comment]
The issue is transpilation in your tooling - you may have to update to webpack 4 to get ES6 support. See this thread for more info: https://github.com/nats-io/nats.ws/issues/68
