### ISSUE TITLE
Detect client disconnect on "backend" side

### ISSUE THREAD

**Issue by a-marchenko** [nats-io/nats.ws#96]
Is there any way to detect if client has disconnected? (something like raw websocket disconnect event)
Is nats server configuration / code modification required for this?
Or is there any other method to detect if nats.ws client disconnected?

**Comment by aricart** [comment]
Absolutely, take a look at https://github.com/nats-io/nats.ws#lifecycleinformational-events.

Note that by default the client will attempt to reconnect - see https://github.com/nats-io/nats.ws#connection-options more specifically `maxReconnectAttempts`, `reconnect`, `waitOnFirstConnect`. Also, you'll want want to handle a close promise resolving `nc.closed().then(()=>{ console.log("client closed");})`. When the client, closes, it will NOT reconnect.
